title: Scientific Python Development Guide
email: guide@scientific-python.org
description: >-
  This guide is maintained by the scientific Python community for the benefit of
  fellow scientists and research software engineers.
github_username: scientific-python
source: docs

# Build settings
markdown: kramdown
theme: "just-the-docs"
plugins:
  - jekyll-feed

# Theme settings

logo: "/assets/images/logo.svg"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Scientific Python Cookie":
    - "https://github.com/scientific-python/cookie"

gh_edit_link: true
gh_edit_link_text: "View source for this page on GitHub."
gh_edit_repository: "https://github.com/scientific-python/cookie"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree" # "tree" or "edit"

callouts:
  warning:
    color: red
    title: Warning
  note:
    color: yellow
    title: Note
  important:
    color: green
    title: Important
  highlight:
    color: blue
